export const ActionTypes = {
  SET_ALL_PRODUCTS: "SET_ALL_PRODUCTS",
  PRODUCTS_DETAILS: "PRODUCTS_DETAILS",
  SELECTED_PRODUCTS: "SELECTED_PRODUCTS",
  REMOVE_SELECTED_PRODUCTS: "REMOVE_SELECTED_PRODUCTS",
  // crud operations
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  UPDATE_CART_QUANTITY: "UPDATE_CART_QUANTITY",
  CLEAR_CART: "CLEAR_CART",
  // Filters & Sorting
  SET_CATEGORY_FILTER: "SET_CATEGORY_FILTER",
  SET_PRICE_FILTER: "SET_PRICE_FILTER",
  SET_RATING_FILTER: "SET_RATING_FILTER",
  SORT_PRODUCTS: "SORT_PRODUCTS",
};
